INSERT INTO filme VALUES
(1,'18','TERROR','SAW','UM BONECO MALUCO QUE MATA GERAL POR MOTIVOS SOCIAIS'),
(2,'10','ANIMACAO','FROZEN','MUIE COM PODER DE GELO COM PROBLEMAS PESSOAIS E AJUDADA PELA IRMA QUE QUASE FALECE'),
(3,'15','SUSPENSE','NAO, NAO OLHE','O FILME DE ALIENIGENA MAIS CONFUSO QUE VOCE VAI ASSISTIR'),
(4,'18','TERROR','MEN','AINDA NAO VI MAS QUERO VER'),
(5,'10','ANIMACAO','TOY STORY','UM MONTE DE BONECO VIVO QUE GOSTA MUITO DO DONO DELES'),
(6,'10','COMEDIA','AMERICAN PIE','FILME QUE ERA ENGRACADO PARA ADOLECENTES DOS ANOS 2000');